// src/utils/label.js

// tout le texte de l'application en differentes langues
const labels = {
	fr :{
		title :'Mon magasin',
		sideAchat : 'Achats',
		sideVente :'Ventes',
		sideStock : 'Stock',
		sideExport: 'Export',
		sideVendeurs : 'Vendeurs',
		sideProduits : 'Produits',
		titleAchat :'Nouvel Achat',
		info:'Informations générales',
		date:'Date',
		heure:'Heure',
		facture:'Facture',
		vendeur:'Vendeur',
		selection:'Sélectionner',
		paid:'Achat payé',
		total:'Total',
		produits:'Produits',
		produit:'Produit',
		quantite:'Quantité',
		pu:'Prix unitaire',
		commission:'Commission',
		ajouter:'Ajouter',
		commentaire:'Commentaire',
		enregistrer:'Enregistrer',
		supprimer:'Supprimer',
		nouveauProduit:'Nouveau produit',
		type:'Type',
		denomination:'Dénomination',
		titleVente:'Nouvelle vente',
		modePaiement: 'Mode de paiement',
		liquide:'Liquide',
		virement:'Virement',
		carte:'Carte B',
		marge:'Marge',
		titleStock:'Gestion du Stock',
		nombreProduits:'Nombre de produits',
		valeurStockAchat:'Valeur du stock (achat)',
		valeurStockVente:'Valeur du stock (vente)',
		margePotentielle:'Marge potentielle',
		recherche:'Rechercher par type ou dénomination...',
		effacerRecherche:'Effacer la recherche',
		actualiser:'Actualiser',
		stock:'Stock',
		prixAchat:'Prix Achat',
		prixVente:'Prix Vente',
		valeurStock:'Valeur Stock',
		annuler:'Annuler',
		unites:'unite(s)',
		modifier:'Modifier',
		aucunProduit:'Aucun produit trouvé',
		effacerFiltres:'Effacer les filtres',
		actions:'Actions',
		nom:'Nom',
		nombreAchats:'Nombre d\'Achats',
	},
	ru :{
		title : 'Мой магазин',
		sideAchat : 'Покупка',
		sideVente :'Продажа',
		sideStock : 'Склад',
		sideExport: 'Экстракт',
		sideVendeurs : 'прибыль',
		sideProduits : 'Товары',
		titleAchat :'Новый куп',
		info:'Общая информация',
		date:'Дата',
		heure:'Время',
		facture:'Счет',
		vendeur:'прибыль',
		selection:'Выбрать',
		paid:'Оплаченный',
		total:'Итого',
		produits:'Товары',
		produit:'Товар',
		quantite:'Кал.',
		pu:'цен. един',
		commission:'Комиссия',
		ajouter:'Добавить',
		commentaire:'Комментарий',
		enregistrer:'Сохранять',
		supprimer:'Удалить',
		nouveauProduit:'Новий товар',
		type:'Тип',
		denomination:'Товар',
		titleVente:'Новый Вант',
		modePaiement: 'Способ оплаты',
		liquide:'Наличные',
		virement:'Перевод',
		carte:'Карта',
		marge:'Marge??',
		titleStock:'Склад',
		nombreProduits:'Количество товаров',
		valeurStockAchat:'Стоимость Склада (покупка)',
		valeurStockVente:'Стоимость Склада (продажа)',
		margePotentielle:'Потенциальная маржа',
		recherche:'Поиск по типу или товару...',
		effacerRecherche:'Очистить поиск',
		actualiser:'Обновить',
		stock:'Склад',
		prixAchat:'Цена при покупке',
		prixVente:'Цена',
		valeurStock:'Стоимость Склада',
		annuler:'Отменить',
		unites:'шт',
		modifier:'Изменить',
		aucunProduit:'Нет товаров',
		effacerFiltres:'Очистить фильтры',
		actions:'Действия',
		nom:'Имя',
		nombreAchats:'Nombre d\'Achats',
	}
};

export default labels;